export default [
	{
		id: '1',
		categoryId: '1',
		title: '常用网址',
		logoPath: 'wujiaoxing',
		hasChild: false
	}, {
		id: '2',
		categoryId: '2',
		title: '动画、特效',
		logoPath: 'animate',
		hasChild: false
	}, {
		id: '18',
		categoryId: '18',
		title: 'API',
		logoPath: 'API',
		hasChild: false
	}, {
		id: '12',
		categoryId: '12',
		title: '工作',
		logoPath: 'work',
		hasChild: false
	}, {
		id: '17',
		categoryId: '17',
		title: '文档编辑',
		logoPath: 'word',
		hasChild: false
	}, {
		id: '10',
		categoryId: '10',
		title: '工具类~',
		logoPath: 'tool',
		hasChild: true,
		children: [{
			id: '100',
			logoPath: 'devolp',
			title: '开发工具'
		}, {
			id: '101',
			logoPath: 'alreadyTool',
			title: '常用工具'
		}, {
			id: '102',
			logoPath: 'zipImg',
			title: '图片处理'
		}, {
			id: '103',
			logoPath: 'webtest',
			title: '网站测试、优化'
		}, {
			id: '104',
			logoPath: 'webManagement',
			title: '网站管理'
		}, {
			id: '105',
			logoPath: 'code',
			title: '常用代码'
		}]
	}, {
		id: '14',
		categoryId: '14',
		title: '协作',
		logoPath: 'youdaoyunxiezuo',
		hasChild: false
	}, {
		id: '19',
		categoryId: '19',
		title: 'Project',
		logoPath: 'project',
		hasChild: false
	}, {
		id: '11',
		categoryId: '11',
		title: '解决方案',
		logoPath: 'plan',
		hasChild: false
	}, {
		id: '15',
		categoryId: '15',
		title: '学习网址',
		logoPath: 'study',
		hasChild: false
	}, {
		id: '2',
		categoryId: '2',
		title: '前端开发',
		hasChild: true,
		logoPath: 'web',
		children: [{
			id: '21',
			logoPath: 'JS',
			title: 'JS框架'
		}, {
			id: '22',
			logoPath: 'element',
			title: 'Ui框架'
		}, {
			id: '23',
			logoPath: 'vue',
			title: 'Vue.js'
		}, {
			id: '24',
			logoPath: 'react',
			title: 'React.js'
		}, {
			id: '25',
			logoPath: 'node',
			title: 'Node.js'
		}, {
			id: '26',
			logoPath: 'plunIn',
			title: 'Js插件库'
		}, {
			id: '27',
			logoPath: 'css',
			title: 'CSS类库'
		}, {
			id: '28',
			logoPath: 'icon',
			title: '字体图标'
		}, {
			id: '29',
			logoPath: 'test',
			title: '面试题'
		}]
	}, {
		id: '3',
		categoryId: '3',
		title: '移动开发',
		hasChild: true,
		logoPath: 'phone',
		children: [{
			id: '31',
			logoPath: 'app',
			title: 'webapp'
		}, {
			id: '32',
			logoPath: 'h5',
			title: 'H5平台'
		}, {
			id: '33',
			logoPath: 'wechat',
			title: '微信、小程序'
		}]
	}, {
		id: '4',
		categoryId: '4',
		title: '后端开发',
		hasChild: true,
		logoPath: 'after',
		children: [{
			id: '41',
			logoPath: 'java',
			title: 'Java'
		}, {
			id: '42',
			logoPath: 'python',
			title: 'Python'
		}]
	}, {
		id: '5',
		categoryId: '5',
		title: 'Ui设计',
		hasChild: true,
		logoPath: 'ui',
		children: [{
			id: '51',
			logoPath: 'uistyle',
			title: '设计风格'
		}, {
			id: '52',
			logoPath: 'product',
			title: '产品设计'
		}, {
			id: '53',
			logoPath: 'uier',
			title: '设计师网址'
		}]
	}, {
		id: '6',
		categoryId: '6',
		title: '前沿技术',
		hasChild: true,
		logoPath: 'teacnoligy',
		children: [{
			id: '61',
			logoPath: 'ai',
			title: '人工智能'
		}, {
			id: '62',
			logoPath: 'ico',
			title: '区块链'
		}, {
			id: '63',
			logoPath: 'Machinelearning',
			title: '机器学习'
		}]
	}, {
		id: '7',
		categoryId: '7',
		title: '阿里系~',
		logoPath: 'ali',
		hasChild: false
	}, {
		id: '8',
		categoryId: '8',
		title: '百度系~',
		logoPath: 'baidu',
		hasChild: false
	}, {
		id: '9',
		categoryId: '9',
		title: '谷歌系~',
		logoPath: 'google',
		hasChild: false
	}, {
		id: '20',
		categoryId: '20',
		title: '腾讯系~',
		logoPath: 'Tencent',
		hasChild: false
	}, {
		id: '13',
		categoryId: '13',
		title: '开发者社区',
		logoPath: 'developer',
		hasChild: false
	}, {
		id: '15',
		categoryId: '15',
		title: '学习网址',
		logoPath: 'study',
		hasChild: false
	}, {
		id: '16',
		categoryId: '16',
		title: '影音、娱乐',
		logoPath: 'music',
		hasChild: false
	}
];
